apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-monitor-clstr0
  region: ap-northeast-2
  version: "1.31"

vpc:
  subnets:
    public:
      ap-northeast-2a:
        id: subnet-0e37444e7a346d033
      ap-northeast-2c:
        id: subnet-051e48bcad72b5442
    private:
      ap-northeast-2a:
        id: subnet-0fedd7208bc8385bd
      ap-northeast-2c:
        id: subnet-062fe56f44c5e487a

iam:
  withOIDC: true

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

managedNodeGroups:
  - name: eks-clstr0-ng1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    amiFamily: AmazonLinux2
